baseurl = "https://alexis2113.github.io/sniffle/"
publishDir: "../alexis2113.github.io"
languageCode = "en-us"
title = "Sniffle"
theme = "nederburg"
googleAnalytics = ""
disqusShortname = "Sniffle"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Home"
    url = "/"
[[menu.main]]
    name = "Post"
    url = "/post/"

[params]
    description = "Notesblah."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

